### ISSUE TITLE
Add basic metadata-step to the template

### ISSUE THREAD

**Issue by cristianvasquez** [zazuko/xrm-xml-workflow#4]
A turtle file with The Dataset + minimal description, and the barnard-rdf step.

```turtle
  <attachMetadata> a p:Step ;
    code:implementedBy [ a code:EcmaScriptModule ;
      code:link <node:barnard59-rdf/metadata.js#append> ] ;
    code:arguments [
      code:name "input"; code:value "../metadata/dataset.ttl"
    ], [
      code:name "dateModified";
      code:value  "TIME_NOW";
    ].
```

- best example: https://gitlab.ldbar.ch/pipelines/bar-alod-ric-o
- Upon completion, create an issue for Metadata about the process.

**Comment by tpluscode** [comment]
Closed in favor of https://github.com/zazuko/barnard59/issues/92
